### ISSUE TITLE
`ripemd160`/`hash160` opcodes fail on some Python versions / operating systems

### ISSUE THREAD

**Issue by theStack** [ajtowns/bllsh#3]
On some operating systems, Python doesn't provide the expected ripemd160 implementation anymore (see e.g. https://github.com/bitcoin/bitcoin/issues/23710, https://github.com/bitcoin/bitcoin/pull/23716 and https://github.com/bitcoin/bips/pull/1616), so the `ripemd160`/`hash160` opcodes fail. E.g. in Ubuntu 22.04 LTS:

```
$ echo "eval (ripemd160 31337)" | ./bllsh
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fas/bips/bllsh/./bllsh", line 51, in wrapper
    return func(*args, **kwargs)
  File "/home/fas/bips/bllsh/./bllsh", line 181, in do_eval
    r = symbll.symbolic_eval(s, self.symbols)
  File "/home/fas/bips/bllsh/symbll.py", line 488, in symbolic_eval
    wi.step()
  File "/home/fas/bips/bllsh/symbll.py", line 450, in step
    fnobj.step(state, c.args, c.localsyms, self)
  File "/home/fas/bips/bllsh/symbll.py", line 198, in step
    r = ResolveSymbol(env, workitem.globalsyms, op.val2)
  File "/home/fas/bips/bllsh/symbll.py", line 169, in ResolveSymbol
    return Func(fn_op, (opcls, opcls.initial_int_state()), opcls.initial_state())
  File "/home/fas/bips/bllsh/opcodes.py", line 288, in initial_int_state
    return hashlib.new("ripemd160")
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
```
The verystable library contains a hand-crafted one, but it only provides immediate finalization without an intermediate `update(...)` interface that bll relies on, so this needs a bit more work.

**Comment by ajtowns** [comment]
Pushed a fix.
